import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google'; // Inter 폰트 추가
import Script from 'next/script'; // Script 컴포넌트 추가
import "./globals.css";
import React from 'react';

// Geist 폰트 설정 (기존과 동일)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Inter 폰트 설정 (next/font/google을 사용하여 최적화)
const inter = Inter({
  subsets: ['latin'],
  display: 'swap', // 폰트 로딩 방식 설정 (필요에 따라 변경)
  variable: '--font-inter', // CSS 변수로 사용하려면 추가
});

export const metadata = {
  title: "Cosmic Nexus", // metadata에서 타이틀 설정
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // html 태그에 Geist 폰트 변수 클래스와 Inter 폰트 클래스를 함께 적용합니다.
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable} ${inter.className}`}>
      <body>
        {/* Tailwind CSS는 일반적으로 PostCSS를 통해 빌드 시점에 처리되므로 CDN은 제거합니다.
            만약 꼭 CDN을 사용해야 한다면 next/script를 사용하세요.
            그러나 Next.js와 Tailwind를 함께 사용할 때는 PostCSS 설정이 기본입니다. */}
        {/* <Script src="https://cdn.tailwindcss.com" strategy="beforeInteractive" /> */}

        {/* Font Awesome 아이콘 라이브러리 (next/script로 로드) */}
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"
          strategy="lazyOnload" // 또는 "afterInteractive"
          crossOrigin="anonymous" // CORS 문제 방지를 위해 추가
        />
        {/* Font Awesome CSS는 globals.css에서 @import 하거나 next/head의 Link 컴포넌트를 사용하세요.
           <link> 태그는 <head> 내부에서 정적으로 처리되는 것이 일반적입니다. */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" crossOrigin="anonymous" referrerPolicy="no-referrer" />


        {/* Inter 폰트는 이미 next/font로 처리되었으므로 <link> 태그는 제거합니다. */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" /> */}

        {children} {/* 모든 페이지 콘텐츠가 여기에 렌더링됩니다 */}
      </body>
    </html>
  );
}